In [1]:
from openairclim.calc_ch4 import calc_swv_mass_conc
from openairclim.calc_swv import *
from matplotlib import pyplot as plt

delta_mass, delta_conc, swv_distribution= calc_swv_mass_conc([10,20,30,40,50])
delta_mass_a,_, swv_distribution_a= calc_swv_mass_conc([1047,1047,1047,1047,1047])
delta_mass_b,_, swv_distribution_b= calc_swv_mass_conc([614,614,614,614,614])
delta_mass_c,_, swv_distribution_c= calc_swv_mass_conc([212,212,212,212,212])
print(delta_mass_a,delta_mass_b,delta_mass_c)

[  0.          19.03685922  71.13436873 149.73118604 243.89457353] [  0.          11.16392699  41.71585712  87.80797348 143.02890941] [ 0.          3.8546458  14.4035207  30.3180625  49.38457458]


In [8]:
import numpy as np

data = {'ch4': [], 'mass': []}
for i in np.arange(0,1000,100):
    ch4_change = i*np.ones(5)
    delta_mass,_, _= calc_swv_mass_conc(ch4_change)
    print(ch4_change,delta_mass)
    data['ch4'].append(ch4_change[-1])
    data['mass'].append(delta_mass[-1])
    plt.scatter(i, delta_mass[-1])
plt.show()    


[0. 0. 0. 0. 0.] [0. 0. 0. 0. 0.]
[100. 100. 100. 100. 100.] [ 0.          1.81822915  6.79411354 14.30097288 23.29461065]
[200. 200. 200. 200. 200.] [ 0.          3.6364583  13.58822707 28.60194576 46.5892213 ]
[300. 300. 300. 300. 300.] [ 0.          5.45468745 20.38234061 42.90291864 69.88383196]
[400. 400. 400. 400. 400.] [ 0.          7.27291661 27.17645415 57.20389152 93.17844261]
[500. 500. 500. 500. 500.] [  0.           9.09114576  33.97056768  71.50486439 116.47305326]
[600. 600. 600. 600. 600.] [  0.          10.90937491  40.76468122  85.80583727 139.76766391]
[700. 700. 700. 700. 700.] [  0.          12.72760406  47.55879476 100.10681015 163.06227457]
[800. 800. 800. 800. 800.] [  0.          14.54583321  54.35290829 114.40778303 186.35688522]
[900. 900. 900. 900. 900.] [  0.          16.36406236  61.14702183 128.70875591 209.65149587]


In [13]:
data['ch4'] = np.array(data['ch4'])
data['ch4']/data['ch4'][1] 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
data['mass'] = np.array(data['mass'])
data['mass']/data['mass'][1] 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
data['mass'][1] 


np.float64(23.29461065233141)